name: consul_kv_dart
description: Implementation of key-value storage client for Hashicorp Consul
version: 1.0.2
homepage: https://github.com/semolex
author: Oleksii Semeshchuk <semolex@live.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  http: "^0.11.3+16"

dev_dependencies:
  test: ^0.12.0
