name: consul_kv_dart
description: Dart client for the Consul KV-store
version: 1.0.0
homepage: https://github.com/semolex
author: Oleksii Semeshchuk <semolex@live.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  http: "^0.11.3+16"

dev_dependencies:
  test: ^0.12.0
